### PR TITLE
Add support for Nova routes

### PR DESCRIPTION
**Pull request by lamalamaMark**

### CODE REVIEW

**Comment by NSpehler** [comment]
May I suggest you use this regex instead? This allows for third-party Nova packages as well:

```// App
Route::any('{all}', function(){
    return view('app');
})->where('all', '^(?![nova-api][nova-vendor]).*$');

**Comment by NSpehler** [comment]
It looks like my above regex is not working. Use this instead:

```// App
Route::any('{all}', function(){
    return view('app');
})->where('all', '^(?!((nova-api)|(nova-vendor))).*$');

**Comment by M-Porter** [comment]
Why are you suggesting changes to an application for a paid piece of software? Seems strange considering this project is showcasing vue-cli-3 with laravel not nova with laravel.

**Comment by DataMarq** [comment]
The above regex route definition isn't working with newest version of Laravel Nova.  It was working with 1.0.6 but not just upgraded to newest 1.0.13 and it stopped working.

**Pull request closed without merging**
